### ISSUE TITLE
Suggestion: [@sexp.unboxed]

### ISSUE THREAD

**Issue by hackwaly** [janestreet/ppx_sexp_conv#36]
```ocaml
type 'a p = 'a * bool
[@@deriving sexp]

type t = 
  | A of int p [@sexp.unboxed] (* Here I want "(A 1 true)", not "(A (1 true))" *)
[@@deriving sexp]
```

**Comment by ceastlund** [comment]
The issue here is that `ppx_sexp_conv` has no way to statically guarantee that `p` produces a list sexp. So you could end up with sexps all defined using `[@@deriving sexp]` which are nevertheless incompatible, and would raise at runtime. You could certainly write this serialization manually, but I don't think we want to add it as a built-in given the limitations.
